theme: jekyll-theme-minimal
title: OuiSync: Secure file-sharing and real-time sync, with or without internet
logo: /assets/img/favicon-32x32.png
description: OuiSync is a free and open source tool enabling file sync and backups between devices, peer-to-peer.
