theme: jekyll-theme-minimal
email: ouisync at equalit dot ie
favicon: true
logo: /assets/img/logo.png
description: OuiSync is a free and open source tool enabling file sync and backups between devices, peer-to-peer.
