theme: jekyll-theme-minimal
email: ouisync at equalit dot ie
favicon: true
logo: /assets/img/logo.png
description: Secure file-sharing and real-time sync, with or without internet.
include: [".well-known"]
